### ISSUE TITLE
Sample for editing or adding attachments

### ISSUE THREAD

**Issue by CalebM1987** [ldanzinger/RuntimeQtSamples#8]
Thank you for posting this repo!  There are some very nice samples in here.  Is there any way you can add a small sample on how to edit or add attachments to a feature service? Maybe you could just add onto the San Diego breweries app by allowing the user to take a photo from their device?  I see the GeoDatabaseFeatureTable has an addAttachment() method, but will the framework automatically access the device camera if it is included in the Capabilities Settings in AppStudio? The QML API docs have information about the classes, but no code samples.  Thanks!

Caleb

**Comment by ldanzinger** [comment]
@CalebM1987 I suggest you download the QML Sample Viewer if you haven't done so already. We have a few different flavors to choose from [here](http://www.arcgis.com/home/search.html?t=content&q=tags:QmlSampleApplicationCurrent&content=all)

Once you have it downloaded, open the "Feature Editing" section, and have a look at the Attachment Editor sample. It shows how to use attachments with the QML API.

**Comment by CalebM1987** [comment]
Thanks for the quick reply!  I just downloaded the sample app for Windows from the link you provided and it appears that the only files I get are distribution files for the Windows platform (i.e. the compiled .DLL's and executable for the app).  Where can I view the QML source files that were used to build the App.  Sorry for the noobish question, I am just getting started with this.  This is the link to what I downloaded:
 http://www.arcgis.com/home/search.html?t=content&q=tags:QmlSampleApplicationCurrent&content=all

Am I missing something here?  Thanks again!

**Comment by ldanzinger** [comment]
No worries, if you run the exe, you will see that each sample has a live view, code example, and description. Go to the sample I suggested in the app, then select the code tab, and you can see the code used for that sample.

**Comment by CalebM1987** [comment]
Oh wow, I completely missed that at the top.  This is great, thank you very much!  You can close this issue now.  I appreciate the help!

**Comment by ldanzinger** [comment]
Cool, no worries. Feel free to chat with us on Geonet under the Qt Native Developers space if you have any questions about the samples or the SDK.

Cheers.
